SELECT *
  FROM [dbo].[TIPO_EJERCICIO]

IF datepart(dw,getdate()) BETWEEN 1 AND 4 --LUNES A JUEVES
	UPDATE [dbo].TIPO_EJERCICIO 
		SET [ESTADO] = 1 
		WHERE ENFOQUE = 'FUERZA'
ELSE
	UPDATE [dbo].TIPO_EJERCICIO 
		SET [ESTADO] = 0 
		WHERE ENFOQUE = 'FUERZA'
	IF datepart(dw,getdate()) BETWEEN 5 AND 7 -- VIERNES A DOMINGO
		UPDATE [dbo].TIPO_EJERCICIO 
			SET [ESTADO] = 1 
			WHERE ENFOQUE = 'CARDIO'
	ELSE 
		UPDATE [dbo].TIPO_EJERCICIO 
			SET [ESTADO] = 0 
			WHERE ENFOQUE = 'CARDIO'
SELECT *
  FROM [dbo].[TIPO_EJERCICIO]