'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ADMINISTRADOR
    Public Property EST_ID As Nullable(Of Integer)
    Public Property ADMIN_ID As Integer
    Public Property ADMIN_NOMBRE As String
    Public Property ADMIN_TELEFONO As String
    Public Property ADMIN_EMAIL As String
    Public Property ADMIN_APELLIDO As String

    Public Overridable Property ESTABLECIMIENTO As ESTABLECIMIENTO

End Class
