'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class COMIDA
    Public Property DIE_ID As Nullable(Of Integer)
    Public Property COM_ID As Integer
    Public Property COM_DESCRIPCION As String
    Public Property COM_HORARIO As String
    Public Property COM_CALORIA As Nullable(Of Single)
    Public Property COM_ESTADO As Nullable(Of Boolean)

    Public Overridable Property DIETA As DIETA

End Class
