'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EJERCICIO
    Public Property EJER_ID As Integer
    Public Property EJER_RUTINA As String

    Public Overridable Property ENTRENAMIENTO As ICollection(Of ENTRENAMIENTO) = New HashSet(Of ENTRENAMIENTO)
    Public Overridable Property TIPO_EJERCICIO As ICollection(Of TIPO_EJERCICIO) = New HashSet(Of TIPO_EJERCICIO)

End Class
