'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOCALIDAD
    Public Property PROV_ID As Nullable(Of Integer)
    Public Property LOCAL_ID As Integer
    Public Property LOCAL_COD_POSTAL As String
    Public Property LOCAL_CUIDAD As String

    Public Overridable Property ESTABLECIMIENTO As ICollection(Of ESTABLECIMIENTO) = New HashSet(Of ESTABLECIMIENTO)
    Public Overridable Property PROVINCIA As PROVINCIA

End Class
