'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GUIA_ENTRENAMIENTOEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GUIA_ENTRENAMIENTOEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ADMINISTRADOR() As DbSet(Of ADMINISTRADOR)
    Public Overridable Property CLIENTE() As DbSet(Of CLIENTE)
    Public Overridable Property COMIDA() As DbSet(Of COMIDA)
    Public Overridable Property DIETA() As DbSet(Of DIETA)
    Public Overridable Property EJERCICIO() As DbSet(Of EJERCICIO)
    Public Overridable Property ENTRENADORES() As DbSet(Of ENTRENADORES)
    Public Overridable Property ENTRENAMIENTO() As DbSet(Of ENTRENAMIENTO)
    Public Overridable Property ESTABLECIMIENTO() As DbSet(Of ESTABLECIMIENTO)
    Public Overridable Property LOCALIDAD() As DbSet(Of LOCALIDAD)
    Public Overridable Property PROVINCIA() As DbSet(Of PROVINCIA)
    Public Overridable Property TIPO_EJERCICIO() As DbSet(Of TIPO_EJERCICIO)

End Class
