'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PROVINCIA
    Public Property PROV_ID As Integer
    Public Property PROV_NOMBRE As String
    Public Property PROV_REGION As String

    Public Overridable Property LOCALIDAD As ICollection(Of LOCALIDAD) = New HashSet(Of LOCALIDAD)

End Class
