'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_EJERCICIO
    Public Property EJER_ID As Nullable(Of Integer)
    Public Property TIP_EJER_ID As Integer
    Public Property EP_EJER_DESCRIPCION As String
    Public Property CALORIAS_GASTADAS As Nullable(Of Double)
    Public Property ENFOQUE As String
    Public Property ESTADO As Nullable(Of Boolean)

    Public Overridable Property EJERCICIO As EJERCICIO

End Class
